backend:
  name: git-gateway
  branch: main

site_url: https://compagniefreres.com
display_url: https://compagniefreres.com

logo_url: /assets/logo-white-green.png

media_folder: "images/uploads"
public_folder: "/images/uploads"

publish_mode: simple

collections:
  - name: "photos"
    label: "Photos du site"
    files:
      - name: "realisations"
        label: "Photos des réalisations"
        file: "data/site.json"
        format: "json"
        fields:
          - label: "Photo façade"
            name: "facade"
            widget: "image"
            required: false
          - label: "Photo intérieur"
            name: "interieur"
            widget: "image"
            required: false
          - label: "Photo finitions"
            name: "finitions"
            widget: "image"
            required: false
